import { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LayoutWrapper from "@/components/LayoutWrapper";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import {
  GlobalCallPopup,
  SocketProvider,
  UserNumberSetup,
} from "@/contexts/SocketContext";

export const metadata: Metadata = {
  title: "Sky Command Center",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" type="image/png" href="/images/logo.png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 dark:bg-gray-900`}
        suppressHydrationWarning
      >
        <SocketProvider>
          <LayoutWrapper>
            <GlobalCallPopup />
            <UserNumberSetup />
            {children}
          </LayoutWrapper>
        </SocketProvider>
      </body>
    </html>
  );
}
